version: "3.6"
services:
  rabbitmq:
    image: rabbitmq:3
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "127.0.0.1:5672:5672"
  go:
    build:
      context: .
      dockerfile: go.Dockerfile
    depends_on:
      - rabbitmq


  python:
    build:
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - ./out:/app/output/
    depends_on:
      - rabbitmq
      - go

  c:
    build:
      context: .
      dockerfile: c.Dockerfile





  #cs:
  #  build:
  #    context: .
  #    dockerfile: cs.Dockerfile

  #erlang:
  #  build:
  #    context: .
  #    dockerfile: erlang.Dockerfile


    #depends_on:
    #  - rabbitmq
    #environment:
    #  - WAIT_HOSTS=rabbitmq
    ##  - WAIT_HOSTS_TIMEOUT=500
    #  - WAIT_SLEEP_INTERVAL=60
     # - WAIT_HOST_CONNECT_TIMEOUT=60

  #haskell:
  #  build:
  #    context: .
  #    dockerfile: haskell.Dockerfile

  #java:
  #  build:
  #    context: .
  #    dockerfile: java.Dockerfile

  #js:
  #  build:
  #    context: .
  #    dockerfile: js.Dockerfile

  #ocaml:
  #  build:
  #    context: .
  #    dockerfile: ocaml.Dockerfile

  #php:
  #  build:
  #    context: .
  #    dockerfile: php.Dockerfile

  #ruby:
  #  build:
  #    context: .
  #    dockerfile: ruby.Dockerfile

  #rust:
  #  build:
  #    context: .
  #    dockerfile: rust.Dockerfile

  #scala:
  #  build:
  #    context: .
  #    dockerfile: scala.Dockerfile

